experiment_name: "baseline"
run_name: "rf_v1"
model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 200
    max_depth: 6
    random_state: 42
metrics:
  - "accuracy"
  - "f1"
mlflow:
  tracking_uri: "sqlite:///mlflow_backend/mlflow.db"
  artifact_store: "mlruns"   # lokalnie; możesz podmienić na S3/Drive

