name: Predict on new data or with new model

on: 
  push:
    branches:
      - main
    paths:
      - 'data/raw/bank-full copy 2.csv'
      - 'data/processed/test.csv'
      - 'ARISA_DSML/predict.py'
      - 'models/catboost_bank.cbm'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing
        run: python ARISA_DSML/preproc.py

      - name: Upload preprocessed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed

  predict:
    runs-on: ubuntu-latest
    needs: preprocess
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: processed-data
          path: data/processed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Resolve champion/challenger
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: python ARISA_DSML/resolve.py

      - name: Run predictions
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: python ARISA_DSML/predict.py

      - name: Upload predictions
        uses: actions/upload-artifact@v4
        with:
          name: predictions
          path: models/preds.csv

      - name: Upload predictions to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_BUCKET }}
        run: |
          pip install awscli
          aws s3 cp models/preds.csv s3://$ARTIFACT_BUCKET/predictions/preds.csv --acl private
