name: Preprocess data and train model

on:
  push:
    branches:
      - main
    paths:
      - 'data/raw/bank-full.csv'
      - 'data/raw/bank-full copy.csv'
      - 'ARISA_DSML/preproc.py'
      - 'ARISA_DSML/train.py'
      - 'models/best_params.pkl'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing
        run: python ARISA_DSML/preproc.py

      - name: Upload preprocessed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed

  train:
    runs-on: ubuntu-latest
    needs: preprocess
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: processed-data
          path: data/processed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Add project root to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: python -m ARISA_DSML.train
